[package]
name = "prc_tools"
version = "0.2.0"
authors = ["Kristóf Ralovich <tade60@freemail.hu>"]
edition = "2024"
license = "MIT"
default-run = "prc-describe"

[dependencies]
prc = { path = ".." }
clap = { version = "4.6", features = ["derive"] }
pretty_env_logger = "0.5"
log = "0.4"
chrono = "0.4"

[[bin]]
name = "prc-describe"
path = "src/prc_describe.rs"


