name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: sudo apt update && sudo apt install lz4 ugrep colordiff
    - name: Build
      run: |
        cargo build --verbose --profile=reldeb --all
        cargo build --verbose --profile=reldeb --tests
    - name: Checkout test data
      uses: actions/checkout@v4
      with:
        repository: ralovich/prc-db
        path: prc-db
    - name: Run tests
      run: |
        cargo test --verbose --profile=reldeb
        cd prc-db/prcs
        #describe=../../target/reldeb/prc_describe INPUT=../../testdata/list_all.txt ../../testdata/prc_describe
        RUST_LOG=info RUST_BACKTRACE=1 describe=../../target/reldeb/prc_describe INPUT=../../testdata/list_all.txt time ../../testdata/prc_describe_mt
        du -d 1 -h
        colordiff -u ../../testdata/expected_all.txt review_summary.txt
