name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --profile=reldeb --all
    - name: Checkout test data
      uses: actions/checkout@v4
      with:
        repository: ralovich/prc-db
        path: prc-db
    - name: Run tests
      run: |
        pwd
        ls -las
        tree
        cargo test --verbose --profile=reldeb
        
